# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='\u542f\u7528\u65e5\u671f')),
                ('status', models.BooleanField(default=True, verbose_name='\u4f7f\u7528\u72b6\u6001')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a',
                'verbose_name_plural': '\u4e3b\u673a\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='HostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP')),
                ('tgt_id', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u6807ID')),
                ('fqdn', models.CharField(blank=True, max_length=50, verbose_name='\u8ba1\u7b97\u673a\u5168\u79f0')),
                ('domain', models.CharField(blank=True, max_length=50, verbose_name='\u57df\u540d')),
                ('hwaddr_interfaces', models.CharField(blank=True, max_length=150, verbose_name='MAC\u5730\u5740')),
                ('cpu_model', models.CharField(blank=True, max_length=50, verbose_name='CPU\u578b\u53f7')),
                ('kernel', models.CharField(blank=True, max_length=50, verbose_name='\u5185\u6838')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('osarch', models.CharField(blank=True, max_length=50, verbose_name='\u7cfb\u7edf\u67b6\u6784')),
                ('osrelease', models.CharField(blank=True, max_length=50, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('productname', models.CharField(blank=True, max_length=50, verbose_name='\u4ea7\u54c1\u578b\u53f7')),
                ('serialnumber', models.CharField(blank=True, max_length=50, verbose_name='\u5e8f\u5217\u53f7')),
                ('server_id', models.CharField(blank=True, max_length=50, verbose_name='\u670d\u52a1ID')),
                ('virtual', models.CharField(blank=True, max_length=50, verbose_name='\u865a\u62df\u73af\u5883')),
                ('salt_status', models.BooleanField(default=False, verbose_name='Salt\u72b6\u6001')),
                ('zbx_status', models.BooleanField(default=False, verbose_name='Zabbix\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u8be6\u7ec6\u4fe1\u606f',
                'verbose_name_plural': '\u4e3b\u673a\u8be6\u7ec6\u4fe1\u606f\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u7ec4',
                'verbose_name_plural': '\u4e3b\u673a\u7ec4\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('type', models.CharField(choices=[('DX', '\u7535\u4fe1'), ('LT', '\u8054\u901a'), ('YD', '\u79fb\u52a8'), ('ZJ', '\u81ea\u5efa')], default='DX', max_length=20, verbose_name='\u673a\u623f\u7c7b\u578b')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='\u673a\u623f\u5730\u5740')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='\u79df\u8d41\u65e5\u671f')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='\u5230\u671f\u65e5\u671f')),
                ('cost', models.CharField(blank=True, max_length=20, verbose_name='\u79df\u8d41\u8d39\u7528')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
                ('brand', models.CharField(blank=True, max_length=30, verbose_name='\u54c1\u724c')),
                ('model', models.CharField(blank=True, max_length=30, verbose_name='\u578b\u53f7')),
                ('ip_out', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='\u5916\u7f51IP\u5730\u5740')),
                ('ip_in', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='\u5185\u7f51IP\u5730\u5740')),
                ('info', models.CharField(blank=True, max_length=100, verbose_name='\u8bf4\u660e')),
                ('url', models.URLField(blank=True, max_length=100, verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='\u5bc6\u7801')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.IDC', verbose_name='\u6240\u5c5e\u673a\u623f')),
            ],
            options={
                'verbose_name': '\u7f51\u7edc\u8bbe\u5907',
                'verbose_name_plural': '\u7f51\u7edc\u8bbe\u5907\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u670d\u52a1\u5668\u540d\u79f0')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='\u673a\u67b6\u4f4d\u7f6e')),
                ('start_date', models.DateField(verbose_name='\u542f\u7528\u65e5\u671f')),
                ('status', models.BooleanField(default=True, verbose_name='\u4f7f\u7528\u72b6\u6001')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.IDC', verbose_name='\u6240\u5c5e\u673a\u623f')),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMDB.HostDetail', verbose_name='IP\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668',
                'verbose_name_plural': '\u670d\u52a1\u5668\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u7c7b\u578b',
                'verbose_name_plural': '\u7cfb\u7edf\u7c7b\u578b\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ManyToManyField(blank=True, to='CMDB.HostGroup', verbose_name='\u6240\u5c5e\u4e3b\u673a\u7ec4'),
        ),
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMDB.HostDetail', verbose_name='IP\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='host',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.Server', verbose_name='\u6240\u5c5e\u670d\u52a1\u5668'),
        ),
        migrations.AddField(
            model_name='host',
            name='system_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.SystemType', verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b'),
        ),
    ]
